language: node_js
node_js:
- stable
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- sequelize db:migrate
after_success:
- npm run coveralls
deploy:
  provider: heroku
  api_key:
    secure: panotm/DNc7P3Zm8FWvK+EICAwgEpDk29ZyVxezHJklhidO7DtIQmtbCbOEL31aKgL3f3bulGqO0VbamOuIRFf0ac6JChzWUALAGsRoRFUBV1Sc/cuYDItlx48aBqiAf8Bdf8ok9u2+XBTPab6AofKlQs3DM7zmFjjMm9kVBb6+JR6h/dMWFreomdApmBmMvd4nCo9xYiyr682U4D/PZJX6S+Fy1KRHXwyki7ZzOiG3ReZQEd/ehIQkLnSqPf/mcnIvuEHEC9UFqhZeAZbDGZh7tD6iMt/+PZrj97bPuGEhLpVA5WMyiCu8j0CS/hjGDOhmdTOrQ3LtOg5u1LTEA+/jzIfg3v8Acn4o591Dv2AWc2PNV5hNRZEViUbHqRsLKEUvV1l24b6otu7dni3Tv7ds6JEgVO5ohB4c8OqpV/EQeESmgEmoNaTM9U7cXnoo4rlZnV7W0BM/SKQTpENkKcQ/ECvXGafNRC4TBybzBvQ59RwZ18ELWKq9T25pe+35i+mH+nIjih97nDtedyV7RExQcVTK77fYcCAIha+8L+Fl2pK0aZo+6GcKYMof/RvQuJA+xGY9F63bJZB27b8wvDf1iAIiCDn1md1fjWsPCYNenocFyS2hbBnrmG4RySSou0bUJeHsUUYwxKUMsHLCK1WIejiB3ZpLaI2QAJFlkDOk=
  app:
    master: lotus-ah
    develop: lotus-ah-staging
  on:
    repo: andela/lotus-ah
  run:
    - sequelize db:migrate